name: boilerplate
description: A flutter boilerplate project created using MobX and Provider.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^0.4.3

  # A composable, Future-based library for making HTTP requests.
  http: ^0.12.0+1

  # This package provides internationalization and localization facilities, including message translation,
  # plurals and genders, date/number formatting and parsing, and bidirectional text
  intl: ^0.15.7

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.0

  # Flogs, a powerful logging framework
  f_logs: ^1.1.1

  # MobX is a library for reactively managing the state of your applications. Use the power of
  # observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^0.1.2
  flutter_mobx: ^0.1.1
  mobx_codegen: ^0.1.0+1

  # An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^1.6.1

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^2.0.0+1

  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^3.0.0

  # A powerful Http client for Dart
  dio: 2.1.6

  # A flexible widget for user notification.
  flushbar: 1.5.3

  # Dependency injection
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject

dependency_overrides:
  analyzer: ^0.36.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"
  build_runner: ^1.3.0

  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: ProductSans
    fonts:
    - asset: assets/fonts/Product-Sans-Regular.ttf
    - asset: assets/fonts/Product-Sans-Italic.ttf
      style: italic
    - asset: assets/fonts/Product-Sans-Bold.ttf
      weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
